version: "2.1"

orbs:
  gcp-cli: circleci/gcp-cli@2.1.1
  
jobs:
  Build:
    docker:
      - image: cimg/node:17.0.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: 
          name: Tests
          command: npm test
      

  Test:
    docker:
      - image: cimg/node:17.0.1
    steps:
      - checkout
      - run: echo "Hello World"
  Test2:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  Test3:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  Push:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
      - gcp-cli/install_and_initialize_cli:
          context: myContext
          executor: gcp-cli/default
workflows:
  "Build_Test_Push":
    jobs:
      - Build
      - Test:
          requires:
            - Build
      - Test2:
          requires:
            - Build
      - Test3:
          requires:
            - Build
      - Push:
          requires:
            - Test
            - Test2
            - Test3
