version: "2.1"

commands:
  check_user:
    steps:
      - run:
          name: 'Check User'
          command: |
            if [[ -z "$BATCHNUM" ]]; then
              echo "Must provide BATCHNUM in environment" 1>&2
              exit 1
            fi
  
jobs:
  Build:
    docker:
      - image: cimg/node:17.0.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: 
          name: Tests
          command: npm test
      

  Test:
    docker:
      - image: cimg/node:17.0.1
    steps:
      - checkout
      - run: echo "Hello World"
  Test2:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  Test3:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  Push:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
      - check_user
      - run: echo $USER
 

workflows:

  "Build_Test_Push":
    jobs:
      - Build
      - Test:
          requires:
            - Build
      - Test2:
          requires:
            - Build
      - Test3:
          requires:
            - Build
      - Push:
          requires:
            - Test
            - Test2
            - Test3
