version: "2.1"
jobs:
  Build:
    docker:
      - image: cimg/node:17.0.1
    steps:
      - checkout
      - run: yarn install
  Test:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  Test2:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  Push:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  outputNode:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
workflows:
  "Build_Test_Push":
    jobs:
      - Build
      - Test:
          requires:
            - Build
      - Test2:
          requires:
            - Build
      - Push:
          requires:
            - Build
      - outputNode:
          requires:
            - Test
            - Test2
            - Push
